import { entryPath } from "./gradePaths.js";
import type { Grade } from "../domain/types.js";
type Fact = [string,string,string];
type Unit = {grade:Grade;subject:string;topic:string;facts:Fact[]};
const units:Unit[] = [
{grade:1,subject:"Science",topic:"Our senses",facts:[
 ["Which part helps you see a rainbow?","Eyes","Eyes detect light and let us see colours."],
 ["Which part helps you hear a bell?","Ears","Ears help us hear sounds."],
 ["Which part helps you smell a flower?","Nose","The nose helps us smell."],
 ["Which part helps you taste a sweet mango?","Tongue","Taste buds on the tongue detect tastes."],
 ["Which part of your body feels a soft cloth?","Skin","Skin senses touch."],
 ["What should you do before touching something that may be hot?","Ask an adult","An adult can help you avoid a burn; do not touch to test it."]]},
{grade:2,subject:"Science",topic:"Parts of a plant",facts:[
 ["Which part usually takes water from soil?","Roots","Roots absorb water from soil."],
 ["Which part holds a plant upright and carries water?","Stem","The stem supports the plant and carries water."],
 ["Which green parts usually make food using sunlight?","Leaves","Green leaves use sunlight to make food."],
 ["Which plant part can grow into a new plant when conditions are suitable?","Seed","A seed contains the beginning of a new plant."],
 ["Which part develops from a flower and often contains seeds?","Fruit","Fruits develop from flowers and often protect seeds."],
 ["Which part of a flowering plant often attracts bees?","Flower","Flowers can attract pollinators such as bees."]]},
{grade:3,subject:"Science",topic:"Animals and their surroundings",facts:[
 ["Which structure lets most fish take oxygen from water?","Gills","Gills take dissolved oxygen from water."],
 ["Which covering helps keep a polar bear warm?","Thick fur","Thick fur helps reduce heat loss in cold places."],
 ["Which feature helps a duck paddle?","Webbed feet","Webbed feet push against water during swimming."],
 ["Which feature helps a bird fly?","Wings","Wings help birds move through the air."],
 ["Which feature helps a camel avoid sinking deeply into sand?","Broad feet","Broad feet spread its weight over more sand."],
 ["What helps a tortoise protect its body?","Hard shell","A hard shell protects the tortoise's soft body."]]},
{grade:4,subject:"Science",topic:"Changes in water",facts:[
 ["Liquid water changing into water vapour is called what?","Evaporation","Evaporation changes liquid water to vapour."],
 ["Water vapour forming liquid drops is called what?","Condensation","Cooling water vapour can form liquid droplets."],
 ["Liquid water becoming ice is called what?","Freezing","Freezing changes liquid water to solid ice."],
 ["Ice becoming liquid water is called what?","Melting","Melting changes solid ice into liquid water."],
 ["Rain falling from clouds is an example of what?","Precipitation","Precipitation includes water falling from clouds as rain or snow."],
 ["Water soaking into the ground is called what?","Infiltration","Infiltration is water entering the soil."]]},
{grade:5,subject:"Science",topic:"Food and nutrition",facts:[
 ["Which nutrient group is a major source of energy in rice?","Carbohydrates","Rice contains starch, a carbohydrate that supplies energy."],
 ["Which nutrients help growth and repair and are supplied by pulses?","Proteins","Pulses provide proteins used for growth and repair."],
 ["Which food components add bulk and help normal bowel movement?","Dietary fibre","Fibre adds bulk to food moving through the digestive system."],
 ["Which nutrient category includes vitamin C?","Vitamins","Vitamin C belongs to the vitamin group."],
 ["Which mineral helps build strong bones and teeth?","Calcium","Calcium is used in bones and teeth."],
 ["Which substance replaces fluid lost in sweat?","Water","Water replaces fluid lost through sweating."]]},
{grade:7,subject:"Science",topic:"Heat transfer",facts:[
 ["Heat travelling along a metal spoon is mainly which process?","Conduction","Conduction transfers heat through a material without bulk movement."],
 ["Warm water rising while cooler water sinks is which process?","Convection","Convection transfers heat through the motion of a fluid."],
 ["Heat reaching Earth from the Sun travels mainly by what?","Radiation","Radiation can transfer energy through empty space."],
 ["What instrument measures temperature?","Thermometer","A thermometer measures temperature."],
 ["What do we call a material that slows heat transfer?","Thermal insulator","An insulator transfers heat poorly."],
 ["When two objects in contact reach the same temperature, what state have they reached?","Thermal equilibrium","At thermal equilibrium there is no net heat transfer between them."]]},
{grade:8,subject:"Science",topic:"Forces in everyday situations",facts:[
 ["What force opposes a book sliding across a desk?","Friction","Friction opposes relative motion between contacting surfaces."],
 ["What force pulls a falling ball toward Earth?","Gravity","Earth's gravitational force pulls the ball toward it."],
 ["What force attracts an iron pin toward a magnet?","Magnetic force","A magnet exerts magnetic force on iron."],
 ["What force can make a rubbed plastic comb attract small paper pieces?","Electrostatic force","Electric charges on the rubbed comb can attract paper."],
 ["What is force divided by the area on which it acts?","Pressure","Pressure is force per unit area."],
 ["Which force is used when a person lifts a school bag by hand?","Muscular force","Muscles supply the force used to lift the bag."]]},
{grade:1,subject:"Social Science",topic:"People who help us",facts:[
 ["Who helps us learn in school?","Teacher","Teachers help children learn."],
 ["Who treats us when we are ill?","Doctor","Doctors examine and treat illnesses."],
 ["Who grows crops for food?","Farmer","Farmers grow crops."],
 ["Who delivers letters?","Postal worker","Postal workers deliver letters and parcels."],
 ["Who helps put out fires?","Firefighter","Firefighters respond to fires."],
 ["Who makes and repairs wooden furniture?","Carpenter","Carpenters work with wood to make and repair furniture."]]},
{grade:2,subject:"Social Science",topic:"Places in our neighbourhood",facts:[
 ["Where do we go to borrow books?","Library","A library lends books for reading."],
 ["Where are letters posted?","Post office","A post office handles letters and parcels."],
 ["Where can a doctor treat patients?","Hospital","Hospitals provide medical care."],
 ["Where do trains usually stop for passengers?","Railway station","Passengers board and leave trains at stations."],
 ["Where do children usually attend classes?","School","Schools provide classes and learning activities."],
 ["Where can families buy vegetables from several stalls?","Market","A market has sellers offering goods such as vegetables."]]},
{grade:3,subject:"Social Science",topic:"Reading a simple map",facts:[
 ["On a map with north at the top, which direction is to the right?","East","East lies to the right when north is at the top."],
 ["On the same map, which direction is to the left?","West","West lies to the left when north is at the top."],
 ["On the same map, which direction is at the bottom?","South","South is opposite north."],
 ["Which direction is opposite south?","North","North and south are opposite directions."],
 ["Which map feature explains what its symbols mean?","Key","A map key explains its symbols."],
 ["Which map feature relates distance on the map to real distance?","Scale","Scale relates map distance to real-world distance."]]},
{grade:4,subject:"Social Science",topic:"Using water responsibly",facts:[
 ["What collects rain from roofs for later use?","Rainwater harvesting","Rainwater harvesting collects and stores rainfall."],
 ["What should be repaired when a tap keeps dripping after it is closed?","A leak","Repairing leaks prevents wasted water."],
 ["Which irrigation method delivers small amounts directly near plant roots?","Drip irrigation","Drip irrigation delivers water close to roots."],
 ["What stores water below the ground in soil and rock spaces?","Groundwater","Groundwater occupies spaces beneath the surface."],
 ["What do we call making used water clean enough for a specified reuse?","Wastewater treatment","Treatment removes contaminants for an intended use."],
 ["What is the land area that drains water toward a common outlet called?","Catchment","A catchment collects runoff that flows toward a shared outlet."]]},
{grade:5,subject:"Social Science",topic:"Living together in a community",facts:[
 ["Which action shows sharing a public space fairly?","Taking turns","Taking turns gives others a fair chance."],
 ["Which action helps keep a public park clean?","Putting litter in a bin","Correct disposal helps keep shared spaces clean."],
 ["Which action helps someone who has not understood a group instruction?","Explaining patiently","Patient explanation helps everyone participate."],
 ["Which action lets a group consider different ideas?","Listening to others","Listening makes different ideas available to the group."],
 ["Which action helps people who use wheelchairs enter a building?","Providing an accessible ramp","An accessible ramp can remove a step barrier."],
 ["Which action respects a queue at a shared service?","Waiting for your turn","Respecting the queue treats people fairly."]]},
{grade:7,subject:"Social Science",topic:"Earth and environment",facts:[
 ["What is Earth's outer solid layer called?","Crust","The crust is Earth's outermost solid layer."],
 ["What is the layer beneath the crust called?","Mantle","The mantle lies below the crust."],
 ["What is Earth's central region called?","Core","The core occupies the central region of Earth."],
 ["What is the blanket of gases around Earth called?","Atmosphere","The atmosphere is the gaseous envelope around Earth."],
 ["What term refers to Earth's water collectively?","Hydrosphere","The hydrosphere includes Earth's water in its different forms."],
 ["What term refers to the zone where life exists?","Biosphere","The biosphere includes the regions where organisms live."]]},
{grade:8,subject:"Social Science",topic:"Understanding democratic institutions",facts:[
 ["Which document sets out India's fundamental governing framework?","Constitution","The Constitution establishes the framework of government and rights."],
 ["Which national institution debates and passes legislation?","Parliament","Parliament is India's national legislature."],
 ["Which institution interprets laws and settles legal disputes?","Judiciary","Courts form the judiciary and interpret laws."],
 ["Which branch implements laws and runs administration?","Executive","The executive implements laws and administers government."],
 ["What process allows voters to choose representatives?","Election","Elections let voters choose representatives."],
 ["What principle means government officials must explain and answer for their actions?","Accountability","Accountability requires officials to answer for their decisions."]]},
{grade:1,subject:"Computer Science",topic:"Getting to know computer devices",facts:[
 ["Which device shows pictures from a computer?","Monitor","A monitor displays pictures and text."],
 ["Which device has letter keys for typing?","Keyboard","A keyboard lets us type letters and numbers."],
 ["Which device moves a pointer when we move it on a desk?","Mouse","A mouse controls the on-screen pointer."],
 ["Which device prints on paper?","Printer","A printer produces paper copies."],
 ["Which device plays sound aloud?","Speaker","A speaker produces sound."],
 ["Which device records your voice?","Microphone","A microphone takes in sound."]]},
{grade:2,subject:"Computer Science",topic:"Choosing input and output devices",facts:[
 ["Which input device is best for typing your name?","Keyboard","A keyboard enters text."],
 ["Which input device captures a photograph?","Camera","A camera captures images as input."],
 ["Which input device records spoken words?","Microphone","A microphone captures sound."],
 ["Which output device gives a paper copy?","Printer","A printer outputs information on paper."],
 ["Which output device shows a video?","Screen","A screen displays visual output."],
 ["Which output device lets you listen privately?","Headphones","Headphones output sound close to your ears."]]},
{grade:3,subject:"Computer Science",topic:"Files and folders",facts:[
 ["What stores a piece of work such as a drawing or document?","File","A file stores a named piece of data."],
 ["What groups related files together?","Folder","Folders organise files."],
 ["Which action records changes to a document?","Save","Saving writes your changes to storage."],
 ["Which action makes a second copy while keeping the original?","Copy","Copying duplicates the file."],
 ["Which action changes a file's name?","Rename","Renaming changes the name without changing the contents."],
 ["Which action relocates a file to another folder without keeping it in the first?","Move","Moving changes a file's location."]]},
{grade:4,subject:"Computer Science",topic:"Describing algorithms",facts:[
 ["What is an ordered set of steps for solving a problem called?","Algorithm","An algorithm specifies ordered steps."],
 ["What repeats a group of instructions?","Loop","A loop runs instructions repeatedly."],
 ["What chooses an action based on whether a condition is true?","If statement","An if statement selects a branch according to a condition."],
 ["What is finding and fixing errors in instructions called?","Debugging","Debugging identifies and corrects errors."],
 ["What breaks a large problem into smaller parts?","Decomposition","Decomposition divides a problem into manageable parts."],
 ["What is checking a solution with sample inputs called?","Testing","Testing checks how a solution behaves on chosen inputs."]]},
{grade:5,subject:"Computer Science",topic:"Protecting digital information",facts:[
 ["What secret should you keep private to protect an account?","Password","A password helps protect access to an account."],
 ["What extra sign-in step asks for a second proof such as a code?","Two-factor authentication","Two-factor authentication adds another verification factor."],
 ["What is a deceptive message trying to steal account details called?","Phishing","Phishing impersonates a trusted source to steal information."],
 ["What copy helps restore a file if the original is lost?","Backup","A backup preserves a separate copy for recovery."],
 ["What permission should you seek before sharing someone's photograph?","Consent","Consent means the person agrees to that use."],
 ["What should you do to end account access on a shared computer?","Sign out","Signing out ends the current signed-in session."]]},
{grade:7,subject:"Computer Science",topic:"Boolean conditions",facts:[
 ["Which operator requires both conditions to be true?","AND","AND is true only when both inputs are true."],
 ["Which operator is true when at least one condition is true?","OR","Inclusive OR needs at least one true input."],
 ["Which operator reverses true and false?","NOT","NOT negates a Boolean value."],
 ["What type has the values true and false?","Boolean","A Boolean represents a truth value."],
 ["What is a named storage location whose value can change?","Variable","A variable stores a value that may change."],
 ["What do we call a rule such as score > 10 that evaluates to true or false?","Condition","A condition is evaluated to choose a path."]]},
{grade:8,subject:"Computer Science",topic:"Understanding structured data",facts:[
 ["In a student table, what is one complete student's row called?","Record","A record groups all fields for one entity."],
 ["What is one named attribute such as date of birth called?","Field","A field stores a particular attribute."],
 ["What identifies each record uniquely?","Primary key","A primary key uniquely identifies a record."],
 ["What operation keeps only rows that meet a condition?","Filter","Filtering selects matching rows."],
 ["What operation puts rows in an order such as A to Z?","Sort","Sorting orders records by chosen values."],
 ["What checks entered data against rules before accepting it?","Validation","Validation checks data against defined constraints."]]}
];
export const GRADE_WORLD_PATHS = units.map((unit)=>entryPath(unit.grade,unit.subject,unit.topic,
  `Identify and apply the key ideas in ${unit.topic.toLowerCase()}.`,
  unit.facts.map(([prompt,answer,explanation],index)=>({prompt,correct:0,
    options:[answer,...[1,2,3].map((offset)=>unit.facts[(index+offset)%unit.facts.length][1])],
    explanation,hint:"Identify the purpose or relationship described in the question, then compare the choices."}))));
